travis:
  secure:
    BINSTAR_TOKEN: WjEQP+F2m5bQDn3jIq0so40IkcjBKW9G5V0pXXfWbm/btaCgyr4A5NuSNDp32+HXzNinVQMHa9o8/ob8e0mgGkpIIxKCJzOH/ntZUBWVLPI8Fx7CiNRJI0K17WvHzI4SQvloRpk/4FmaiXoWmu/VPf/BQ/tTNtA2wImXMkUHrXOTDacaCfcEf1X7ayeORihBiCCix+IbtHdShZhfc65dGS017IcwIfNQTrqH27HsTwqZN8ddugaiIEBuvN3XDnAH1BCh+yeHTQz53hzo49iGJxNolzNcusxCoDWqREDJzLoYsbp44lFbG+Gijp2D9qMyRMzh74K9kWLK75Vczq/++jFUY9sI75jzQWcCkenz/IVt9RNFRKSaKPB3X2Y2jw6bIf75RfV1cZsqatX0xAwEaABuLQFy/wyVASQ45IFrhNMLC2qBvejPOwevKnpycjts1G8wuvJVNzQWyz4WP6mjdgU9khm/vPz7IL1qRcx96VWsF+yFhiwbYqCdwZaB4Iik5+Fy6WuuGjmkZglClYXgtGqYMfYaoKnh4hTYJOVm/gqydDNRO/YrFsZM0MES4c9teT5sDn7pTp8gTrMiag+HSLF8C2G/3Z9Bn8Wxwpxlkbo04R77aNLrThfHWuk373wAdBaJ4bSJAEmyNfJCjqD0yrmtlf+FPQABKZ/YiY1gK64=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
