travis:
  secure:
    BINSTAR_TOKEN: dtAVDwNHIc5sbBSMSOCgkeceEjSEyeiQ6nV+QLdxglrYB6BXeYMiJvSjZrP4Y3N2gRc23uHC9ZXNXJGRr0rNTroF8oIIKb3XBsS4d2/10FJ1NuhoNzh3HThB/l6zWwv02n/DVMLLcAc0WSJpji4wAUu+cjOR8JyoOdcbDHVmSobeqCXS/YRNz2V1AFJg76QP5wRtkmJ++fRwd3K4PvLoGRSmWkxo0sBp0xBjUFC8gy9e7ywkqPXi5Jw5/eTBHFDR2TYT4AleGNa54iL3P3Kz2ZetsKHm/ObmEpFkfAeqGQXQ1ic70Ta+bUq/wkH3+3GuNxNSVMbAzV2UYmUBu39S0s6TrFcR8B4hY9Sy3+XnIy2a5DIP909eNr/oS6WQDS7GlUbMGN7ok/XOjGvuA90rh3MPgm6S8SXwAeJP6aynWdB0DnjQ1t5zffGCShPDpb+28gnE7hMHozztw/2Po0Ug5NHpJlwRl23eItnEhzNn+X015oJZC6mhICgsvzgLvNq/l4oANcOfxj5Nck0cSPDKMJEf3m5km9lbKNtUL8Y1mzu4SqYBLnMYAgQoHiVqfsHCHaydb46mmzE5OslohpKZbRO6sr9VmKg/zqOLSk9x0HZnX+QiJ08OHmDCdwDtz2QxxsH6EH/ij6LaSEKWcTicKhxhbGd6ldxYKVYqTUtyXRA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
